services:
  db:
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_USER: timeline
      POSTGRES_PASSWORD: timeline
      POSTGRES_DB: timeline
    ports:
      - 5432:5432
    volumes:
      - timeline-data:/var/lib/postgresql/data

volumes:
  timeline-data:
    external: false
