// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"timeline/backend/ent/account"
	"timeline/backend/ent/predicate"
	"timeline/backend/ent/timeline"
	"timeline/backend/ent/user"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AccountUpdate is the builder for updating Account entities.
type AccountUpdate struct {
	config
	hooks    []Hook
	mutation *AccountMutation
}

// Where appends a list predicates to the AccountUpdate builder.
func (au *AccountUpdate) Where(ps ...predicate.Account) *AccountUpdate {
	au.mutation.Where(ps...)
	return au
}

// SetName sets the "name" field.
func (au *AccountUpdate) SetName(s string) *AccountUpdate {
	au.mutation.SetName(s)
	return au
}

// SetNillableName sets the "name" field if the given value is not nil.
func (au *AccountUpdate) SetNillableName(s *string) *AccountUpdate {
	if s != nil {
		au.SetName(*s)
	}
	return au
}

// SetPreviewlyToken sets the "previewly_token" field.
func (au *AccountUpdate) SetPreviewlyToken(s string) *AccountUpdate {
	au.mutation.SetPreviewlyToken(s)
	return au
}

// SetNillablePreviewlyToken sets the "previewly_token" field if the given value is not nil.
func (au *AccountUpdate) SetNillablePreviewlyToken(s *string) *AccountUpdate {
	if s != nil {
		au.SetPreviewlyToken(*s)
	}
	return au
}

// SetAvatarID sets the "avatar_id" field.
func (au *AccountUpdate) SetAvatarID(i int) *AccountUpdate {
	au.mutation.ResetAvatarID()
	au.mutation.SetAvatarID(i)
	return au
}

// SetNillableAvatarID sets the "avatar_id" field if the given value is not nil.
func (au *AccountUpdate) SetNillableAvatarID(i *int) *AccountUpdate {
	if i != nil {
		au.SetAvatarID(*i)
	}
	return au
}

// AddAvatarID adds i to the "avatar_id" field.
func (au *AccountUpdate) AddAvatarID(i int) *AccountUpdate {
	au.mutation.AddAvatarID(i)
	return au
}

// ClearAvatarID clears the value of the "avatar_id" field.
func (au *AccountUpdate) ClearAvatarID() *AccountUpdate {
	au.mutation.ClearAvatarID()
	return au
}

// SetAbout sets the "about" field.
func (au *AccountUpdate) SetAbout(s string) *AccountUpdate {
	au.mutation.SetAbout(s)
	return au
}

// SetNillableAbout sets the "about" field if the given value is not nil.
func (au *AccountUpdate) SetNillableAbout(s *string) *AccountUpdate {
	if s != nil {
		au.SetAbout(*s)
	}
	return au
}

// ClearAbout clears the value of the "about" field.
func (au *AccountUpdate) ClearAbout() *AccountUpdate {
	au.mutation.ClearAbout()
	return au
}

// AddTimelineIDs adds the "timeline" edge to the Timeline entity by IDs.
func (au *AccountUpdate) AddTimelineIDs(ids ...int) *AccountUpdate {
	au.mutation.AddTimelineIDs(ids...)
	return au
}

// AddTimeline adds the "timeline" edges to the Timeline entity.
func (au *AccountUpdate) AddTimeline(t ...*Timeline) *AccountUpdate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return au.AddTimelineIDs(ids...)
}

// SetUserID sets the "user" edge to the User entity by ID.
func (au *AccountUpdate) SetUserID(id int) *AccountUpdate {
	au.mutation.SetUserID(id)
	return au
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (au *AccountUpdate) SetNillableUserID(id *int) *AccountUpdate {
	if id != nil {
		au = au.SetUserID(*id)
	}
	return au
}

// SetUser sets the "user" edge to the User entity.
func (au *AccountUpdate) SetUser(u *User) *AccountUpdate {
	return au.SetUserID(u.ID)
}

// Mutation returns the AccountMutation object of the builder.
func (au *AccountUpdate) Mutation() *AccountMutation {
	return au.mutation
}

// ClearTimeline clears all "timeline" edges to the Timeline entity.
func (au *AccountUpdate) ClearTimeline() *AccountUpdate {
	au.mutation.ClearTimeline()
	return au
}

// RemoveTimelineIDs removes the "timeline" edge to Timeline entities by IDs.
func (au *AccountUpdate) RemoveTimelineIDs(ids ...int) *AccountUpdate {
	au.mutation.RemoveTimelineIDs(ids...)
	return au
}

// RemoveTimeline removes "timeline" edges to Timeline entities.
func (au *AccountUpdate) RemoveTimeline(t ...*Timeline) *AccountUpdate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return au.RemoveTimelineIDs(ids...)
}

// ClearUser clears the "user" edge to the User entity.
func (au *AccountUpdate) ClearUser() *AccountUpdate {
	au.mutation.ClearUser()
	return au
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (au *AccountUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, au.sqlSave, au.mutation, au.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (au *AccountUpdate) SaveX(ctx context.Context) int {
	affected, err := au.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (au *AccountUpdate) Exec(ctx context.Context) error {
	_, err := au.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (au *AccountUpdate) ExecX(ctx context.Context) {
	if err := au.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (au *AccountUpdate) check() error {
	if v, ok := au.mutation.PreviewlyToken(); ok {
		if err := account.PreviewlyTokenValidator(v); err != nil {
			return &ValidationError{Name: "previewly_token", err: fmt.Errorf(`ent: validator failed for field "Account.previewly_token": %w`, err)}
		}
	}
	return nil
}

func (au *AccountUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := au.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(account.Table, account.Columns, sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt))
	if ps := au.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := au.mutation.Name(); ok {
		_spec.SetField(account.FieldName, field.TypeString, value)
	}
	if value, ok := au.mutation.PreviewlyToken(); ok {
		_spec.SetField(account.FieldPreviewlyToken, field.TypeString, value)
	}
	if value, ok := au.mutation.AvatarID(); ok {
		_spec.SetField(account.FieldAvatarID, field.TypeInt, value)
	}
	if value, ok := au.mutation.AddedAvatarID(); ok {
		_spec.AddField(account.FieldAvatarID, field.TypeInt, value)
	}
	if au.mutation.AvatarIDCleared() {
		_spec.ClearField(account.FieldAvatarID, field.TypeInt)
	}
	if value, ok := au.mutation.About(); ok {
		_spec.SetField(account.FieldAbout, field.TypeString, value)
	}
	if au.mutation.AboutCleared() {
		_spec.ClearField(account.FieldAbout, field.TypeString)
	}
	if au.mutation.TimelineCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.TimelineTable,
			Columns: []string{account.TimelineColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(timeline.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.RemovedTimelineIDs(); len(nodes) > 0 && !au.mutation.TimelineCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.TimelineTable,
			Columns: []string{account.TimelineColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(timeline.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.TimelineIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.TimelineTable,
			Columns: []string{account.TimelineColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(timeline.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if au.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   account.UserTable,
			Columns: []string{account.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   account.UserTable,
			Columns: []string{account.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, au.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{account.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	au.mutation.done = true
	return n, nil
}

// AccountUpdateOne is the builder for updating a single Account entity.
type AccountUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccountMutation
}

// SetName sets the "name" field.
func (auo *AccountUpdateOne) SetName(s string) *AccountUpdateOne {
	auo.mutation.SetName(s)
	return auo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (auo *AccountUpdateOne) SetNillableName(s *string) *AccountUpdateOne {
	if s != nil {
		auo.SetName(*s)
	}
	return auo
}

// SetPreviewlyToken sets the "previewly_token" field.
func (auo *AccountUpdateOne) SetPreviewlyToken(s string) *AccountUpdateOne {
	auo.mutation.SetPreviewlyToken(s)
	return auo
}

// SetNillablePreviewlyToken sets the "previewly_token" field if the given value is not nil.
func (auo *AccountUpdateOne) SetNillablePreviewlyToken(s *string) *AccountUpdateOne {
	if s != nil {
		auo.SetPreviewlyToken(*s)
	}
	return auo
}

// SetAvatarID sets the "avatar_id" field.
func (auo *AccountUpdateOne) SetAvatarID(i int) *AccountUpdateOne {
	auo.mutation.ResetAvatarID()
	auo.mutation.SetAvatarID(i)
	return auo
}

// SetNillableAvatarID sets the "avatar_id" field if the given value is not nil.
func (auo *AccountUpdateOne) SetNillableAvatarID(i *int) *AccountUpdateOne {
	if i != nil {
		auo.SetAvatarID(*i)
	}
	return auo
}

// AddAvatarID adds i to the "avatar_id" field.
func (auo *AccountUpdateOne) AddAvatarID(i int) *AccountUpdateOne {
	auo.mutation.AddAvatarID(i)
	return auo
}

// ClearAvatarID clears the value of the "avatar_id" field.
func (auo *AccountUpdateOne) ClearAvatarID() *AccountUpdateOne {
	auo.mutation.ClearAvatarID()
	return auo
}

// SetAbout sets the "about" field.
func (auo *AccountUpdateOne) SetAbout(s string) *AccountUpdateOne {
	auo.mutation.SetAbout(s)
	return auo
}

// SetNillableAbout sets the "about" field if the given value is not nil.
func (auo *AccountUpdateOne) SetNillableAbout(s *string) *AccountUpdateOne {
	if s != nil {
		auo.SetAbout(*s)
	}
	return auo
}

// ClearAbout clears the value of the "about" field.
func (auo *AccountUpdateOne) ClearAbout() *AccountUpdateOne {
	auo.mutation.ClearAbout()
	return auo
}

// AddTimelineIDs adds the "timeline" edge to the Timeline entity by IDs.
func (auo *AccountUpdateOne) AddTimelineIDs(ids ...int) *AccountUpdateOne {
	auo.mutation.AddTimelineIDs(ids...)
	return auo
}

// AddTimeline adds the "timeline" edges to the Timeline entity.
func (auo *AccountUpdateOne) AddTimeline(t ...*Timeline) *AccountUpdateOne {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return auo.AddTimelineIDs(ids...)
}

// SetUserID sets the "user" edge to the User entity by ID.
func (auo *AccountUpdateOne) SetUserID(id int) *AccountUpdateOne {
	auo.mutation.SetUserID(id)
	return auo
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (auo *AccountUpdateOne) SetNillableUserID(id *int) *AccountUpdateOne {
	if id != nil {
		auo = auo.SetUserID(*id)
	}
	return auo
}

// SetUser sets the "user" edge to the User entity.
func (auo *AccountUpdateOne) SetUser(u *User) *AccountUpdateOne {
	return auo.SetUserID(u.ID)
}

// Mutation returns the AccountMutation object of the builder.
func (auo *AccountUpdateOne) Mutation() *AccountMutation {
	return auo.mutation
}

// ClearTimeline clears all "timeline" edges to the Timeline entity.
func (auo *AccountUpdateOne) ClearTimeline() *AccountUpdateOne {
	auo.mutation.ClearTimeline()
	return auo
}

// RemoveTimelineIDs removes the "timeline" edge to Timeline entities by IDs.
func (auo *AccountUpdateOne) RemoveTimelineIDs(ids ...int) *AccountUpdateOne {
	auo.mutation.RemoveTimelineIDs(ids...)
	return auo
}

// RemoveTimeline removes "timeline" edges to Timeline entities.
func (auo *AccountUpdateOne) RemoveTimeline(t ...*Timeline) *AccountUpdateOne {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return auo.RemoveTimelineIDs(ids...)
}

// ClearUser clears the "user" edge to the User entity.
func (auo *AccountUpdateOne) ClearUser() *AccountUpdateOne {
	auo.mutation.ClearUser()
	return auo
}

// Where appends a list predicates to the AccountUpdate builder.
func (auo *AccountUpdateOne) Where(ps ...predicate.Account) *AccountUpdateOne {
	auo.mutation.Where(ps...)
	return auo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (auo *AccountUpdateOne) Select(field string, fields ...string) *AccountUpdateOne {
	auo.fields = append([]string{field}, fields...)
	return auo
}

// Save executes the query and returns the updated Account entity.
func (auo *AccountUpdateOne) Save(ctx context.Context) (*Account, error) {
	return withHooks(ctx, auo.sqlSave, auo.mutation, auo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (auo *AccountUpdateOne) SaveX(ctx context.Context) *Account {
	node, err := auo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (auo *AccountUpdateOne) Exec(ctx context.Context) error {
	_, err := auo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (auo *AccountUpdateOne) ExecX(ctx context.Context) {
	if err := auo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (auo *AccountUpdateOne) check() error {
	if v, ok := auo.mutation.PreviewlyToken(); ok {
		if err := account.PreviewlyTokenValidator(v); err != nil {
			return &ValidationError{Name: "previewly_token", err: fmt.Errorf(`ent: validator failed for field "Account.previewly_token": %w`, err)}
		}
	}
	return nil
}

func (auo *AccountUpdateOne) sqlSave(ctx context.Context) (_node *Account, err error) {
	if err := auo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(account.Table, account.Columns, sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt))
	id, ok := auo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Account.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := auo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, account.FieldID)
		for _, f := range fields {
			if !account.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != account.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := auo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := auo.mutation.Name(); ok {
		_spec.SetField(account.FieldName, field.TypeString, value)
	}
	if value, ok := auo.mutation.PreviewlyToken(); ok {
		_spec.SetField(account.FieldPreviewlyToken, field.TypeString, value)
	}
	if value, ok := auo.mutation.AvatarID(); ok {
		_spec.SetField(account.FieldAvatarID, field.TypeInt, value)
	}
	if value, ok := auo.mutation.AddedAvatarID(); ok {
		_spec.AddField(account.FieldAvatarID, field.TypeInt, value)
	}
	if auo.mutation.AvatarIDCleared() {
		_spec.ClearField(account.FieldAvatarID, field.TypeInt)
	}
	if value, ok := auo.mutation.About(); ok {
		_spec.SetField(account.FieldAbout, field.TypeString, value)
	}
	if auo.mutation.AboutCleared() {
		_spec.ClearField(account.FieldAbout, field.TypeString)
	}
	if auo.mutation.TimelineCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.TimelineTable,
			Columns: []string{account.TimelineColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(timeline.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.RemovedTimelineIDs(); len(nodes) > 0 && !auo.mutation.TimelineCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.TimelineTable,
			Columns: []string{account.TimelineColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(timeline.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.TimelineIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.TimelineTable,
			Columns: []string{account.TimelineColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(timeline.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if auo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   account.UserTable,
			Columns: []string{account.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   account.UserTable,
			Columns: []string{account.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Account{config: auo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, auo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{account.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	auo.mutation.done = true
	return _node, nil
}
