// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package previewly

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

// createTokenResponse is returned by createToken on success.
type createTokenResponse struct {
	CreateToken string `json:"createToken"`
}

// GetCreateToken returns createTokenResponse.CreateToken, and is useful for accessing the field via an interface.
func (v *createTokenResponse) GetCreateToken() string { return v.CreateToken }

// The query or mutation executed by createToken.
const createToken_Operation = `
mutation createToken {
	createToken
}
`

func createToken(
	ctx_ context.Context,
	client_ graphql.Client,
) (*createTokenResponse, error) {
	req_ := &graphql.Request{
		OpName: "createToken",
		Query:  createToken_Operation,
	}
	var err_ error

	var data_ createTokenResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}
