name: govulncheck

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  govulncheck:
    name: govulncheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24.2"
          cache: false
      - uses: golang/govulncheck-action@v1
