// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Account is the predicate function for account builders.
type Account func(*sql.Selector)

// Event is the predicate function for event builders.
type Event func(*sql.Selector)

// Tag is the predicate function for tag builders.
type Tag func(*sql.Selector)

// Timeline is the predicate function for timeline builders.
type Timeline func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
